name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Validate JSON configurations
      run: |
        python -c "import json; json.load(open('examples/deployments.json'))"
        python -c "import json; json.load(open('examples/simple-deployment.json'))"
    
    - name: Run tests
      run: |
        python -m unittest test_controller.py -v
    
    - name: Check Python syntax
      run: |
        python -m py_compile controller.py

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        docker build -t pod-manager:latest .
    
    - name: Test Docker image
      run: |
        docker images | grep pod-manager
